#!/usr/bin/env bash

usage()
{
  PGM=$(basename $0)
  echo "Usage: $PGM [OPTS] <file> <file|dir>"
  echo "Where OPTS:"
  echo "  -v : verbose; show differences"
  echo "  -h : this help text"
}

QUIET=-q
while getopts :vh OPT; do
  case $OPT in
    v) unset QUIET ;;
    h) usage; exit ;;
    *) echo "ERROR: unknown argument '-$OPTARG'"; exit 22 ;;
  esac
done
shift $((OPTIND-1))

[[ 2 -ne $# ]] && { echo "Invalid command line"; exit 22; }

F1=$1
F2=$2
[[ -r $F1 ]] || { echo "File does not exist: $F1"; exit 2; }
[[ -r $F2 ]] || { echo "File/dir does not exist: $F2"; exit 2; }
[[ -d $F1 ]] && { echo "File1 is a directory: $F1"; exit 2; }

# if F2 is a dir; append filename to it
if [[ -d $F2 ]]; then
  F2="${F2}/$(basename $F1)"
  [[ -r $F2 ]] || { echo "File2 does not exist: $F2"; exit 2; }
fi

NAMES="$F1 and $F2"
# Linux uses -c, mac uses -f for the same functionality
# detect by capability since GNU coreutils may be installed on macOS
stat -c "%d" /dev/null &>/dev/null && STAT_FLG=-c || STAT_FLG=-f
I1=$(stat $STAT_FLG "%d-%i" "$F1")
I2=$(stat $STAT_FLG "%d-%i" "$F2")
[[ $I1 == $I2 ]] && { echo "Files ${NAMES} have the same device/inode"; exit; }

diff $QUIET $F1 $F2 2>/dev/null
RC=$?
if [[ 0 -eq $RC ]]; then
    echo "Files ${NAMES} are identical"
fi

exit $RC

