#!/bin/bash

usage()
{
  echo "Usage: $(basename $0) [OPTIONS] <file>"
  echo "OPTIONS:"
  echo "  -c : cumulative sums"
  echo "  -m : force use of md5sum (instead of shasum)"
  echo "  -w : ignore whitespace"
  echo "  -W : ignore whitespace and show contents w/o whitespace"
  echo "  -h : this help"
}

trim()
{
  local var="$*"
  # remove leading whitespace characters
  var="${var#"${var%%[![:space:]]*}"}"
  # remove trailing whitespace characters
  var="${var%"${var##*[![:space:]]}"}"
  echo -n "$var"
}

unset CUME TRIM
HASHCMD=shasum
while getopts :cmvwWh opt
do
  case "$opt" in
    c) CUME=1 ;;
    m) HASHCMD=md5sum ;;
    w) TRIM=1 ;;
    W) TRIM=1; SHOW_TRIM=1 ;;
    h) usage; exit ;;
    *) echo "ERROR: unknown option: '-$OPTARG'"; exit 22 ;;
  esac
done
shift $((OPTIND-1))

# if SHASUM is not available, use md5sum
if [[ "shasum" == $HASHCMD ]]; then
  if ! type -f shasum &> /dev/null; then
    HASHCMD=md5sum
  fi
fi

[[ 1 != $# ]] && { echo "ERROR: Invalid command line"; exit 22; }

LNUM=0
unset LINES
while IFS='' read -r LINE || [[ -n "$LINE" ]]; do
  if [[ -n $TRIM ]]; then
    ORIG=$LINE
    LINE=$(trim $LINE)
    [[ -n $SHOW_TRIM ]] && ORIG=$LINE
  fi
  LNUM=$((LNUM+1))
  fmtln=$(printf "%06d" $LNUM)
  TAIL=" : $ORIG"
  if [[ -n $CUME ]]; then
    if [[ -n $LINES ]]; then LINES="${LINES}\n"; fi
    LINES="${LINES}${LINE}"
    LINE=${LINES}
  fi
  echo "$fmtln: $(echo "$LINE" | $HASHCMD | cut -f1 -d' ')$TAIL"
done < "$1"

