#!/usr/bin/env bash

usage()
{
  echo "Usage: $(basename "$0") [-h] <arg1> [arg2..]"
  echo "Where:"
  echo "  -h : This help text"
}

while getopts h OPT; do
  case $OPT in
    h) usage; exit ;;
    *) exit 22 ;;
  esac
done
shift $((OPTIND-1))


OPTS=-ef
[[ ! -d $HOME/tmp ]] && mkdir -p "$HOME/tmp"
[[ -d $HOME/tmp ]] && TMPDIR=$HOME/tmp || TMPDIR=/tmp

if [[ $# == 0 ]]; then
  ps ${OPTS}
else
  # mktemp -p is unsupported on macOS; a full-path template puts the file in TMPDIR
  TMPF=$(mktemp "${TMPDIR}/psef.XXXXXXXXXXX")
  trap 'rm -f "$TMPF"' EXIT
  ps ${OPTS} > "${TMPF}"
  HEAD=0
  while [[ $# -gt 0 ]]; do
    TASKNAME=$1
    shift
    #DATA=$(fgrep ${TASKNAME} ${TMPF} | fgrep -v " $$ ")
    DATA=$(grep -Fw "${TASKNAME}" "${TMPF}" | grep -Fv " $$ ")
    #while [[ $# -gt 0 ]]; do
    #  DATA=$(fgrep $1 $(echo "${DATA}"))
    #done
    if [[ -n "${DATA}" ]]; then
      if [[ HEAD -eq 0 ]]; then
        head -1 "${TMPF}"
        HEAD=1
      fi
      echo "${DATA}"
    fi
  done
fi
