#!/usr/bin/env bash

usage()
{
  PGM=$(basename $0)
  echo "Usage: $PGM [OPTS] <search> [file[s]]"
  echo "Where OPTS:"
  echo "  -c     : match c/cpp source files (default all or [files])"
  echo "  -d dir : specify directory to search (default: .)"
  echo "  -i     : ignore case"
  echo "  -l     : only print files with matches"
  echo "  -v     : verbose mode"
  echo "  -h     : this help text"
}

PATS=()
WHERE=.
unset VERBOSE OPT_I OPT_L
while getopts cd:ilvh OPT
do
  case "$OPT" in
    c) PATS=("*.{c,cpp,h}") ;;
    d) WHERE=$OPTARG ;;
    i) OPT_I="-i" ;;
    l) OPT_L="-l" ;;
    v) VERBOSE=1 ;;
    h) usage; exit ;;
    *) exit 22 ;;
  esac
done
shift $((OPTIND-1))

[[ $# -eq 0 ]] && { echo "Nothing specified"; exit 22; }

if ! type -f rgrep > /dev/null 2>&1; then
  echo "Unable to find required rgrep command"
  exit 127
fi


if [[ ${#PATS[@]} -gt 0 ]]; then
  [[ -n $VERBOSE ]] && set -x
  exec rgrep $OPT_I $OPT_L "$WHERE" "$1" "${PATS[@]}"
else
  [[ -n $VERBOSE ]] && set -x
  exec rgrep $OPT_I $OPT_L "$WHERE" "$1" "${@:2}"
fi

